export interface Product {
  id: string
  name: string
  price: number
  category: string
  description: string
  details: string[]
  inStock: boolean

  // ✅ NEW FIELDS
  onSale: boolean
  salePrice?: number
  discountPercent?: number
  images: string[] // multiple images instead of single image
}



// export const products: Product[] = [
//   {
//     id: '1',
//     name: 'Minimal Leather Jacket',
//     price: 1200,
//     category: 'Fashion',
//     description:
//       'Crafted from premium Italian leather, this minimal jacket epitomizes timeless elegance.',
//     details: [
//       'Premium Italian leather',
//       'Minimalist button closure',
//       'Two side pockets',
//       'Adjustable waist straps',
//       'Dry clean only',
//     ],
//     inStock: true,

//     // NEW
//     onSale: true,
//     salePrice: 999,
//     discountPercent: 17,
//     images: [
//       '/images/product-1.png',
//       '/images/product-1.png',
//       '/images/product-1-3.png',
//     ],
//   },
//   {
//     id: '2',
//     name: 'Premium Sunglasses',
//     price: 50,
//     category: 'Accessories',
//     description: 'UV-protected premium sunglasses with handcrafted frames.',
//     details: [
//       'UV 400 protection',
//       'Handcrafted frames',
//       'Glass lenses',
//       'Includes premium case',
//       'Anti-reflective coating',
//     ],
//     inStock: true,

//     onSale: false,
//     images: [
//       '/images/product-2.png',
//       '/images/product-2-2.png',
//     ],
//   },
//   {
//     id: '3',
//     name: 'Silk Evening Dress',
//     price: 890,
//     category: 'Fashion',
//     description: 'An elegant silk evening dress perfect for special occasions.',
//     details: [
//       '100% mulberry silk',
//       'Hand-finished seams',
//       'Adjustable straps',
//       'Back zip closure',
//       'Lining included',
//     ],
//     inStock: true,

//     onSale: true,
//     salePrice: 799,
//     discountPercent: 10,
//     images: [
//       '/images/product-3.png',
//       '/images/product-3-2.png',
//     ],
//   },
//   {
//     id: '4',
//     name: 'Designer Handbag',
//     price: 1450,
//     category: 'Accessories',
//     description:
//       'A structured designer handbag crafted from premium leather.',
//     details: [
//       'Premium cream leather',
//       'Gold-plated hardware',
//       'Interior zip pocket',
//       'Adjustable shoulder strap',
//       'Dust bag included',
//     ],
//     inStock: false,

//     onSale: false,
//     images: [
//       '/images/product-4.png',
//       '/images/product-4-2.png',
//     ],
//   },
// ]


export const products: Product[] = [
  {
   id: '1',
  name: 'Purple Embroidered Straight Kurta Trouser & Dupatta Set',
  price: 549,
  category: 'Women Ethnic Wear',
  description:
    'Elevate your ethnic wardrobe with this elegant purple embroidered straight kurta set. Crafted from a soft, breathable fabric, the ensemble features intricate golden thread embroidery on the neckline, sleeves, and dupatta border. Paired with matching solid trousers and a beautifully embroidered dupatta, this three-piece outfit is perfect for festive celebrations, weddings, family gatherings, and traditional occasions.',
  details: [
    '3-piece ethnic wear set',
    'Straight-fit embroidered kurta',
    'Matching solid trousers',
    'Embroidered dupatta with decorative border',
    'Rich royal purple color',
    'Round neckline with detailed embroidery',
    'Three-quarter sleeves',
    'Golden thread embroidered motifs',
    'Comfortable regular fit',
    'Soft and lightweight fabric',
    'Perfect for festive and ethnic occasions',
    'Easy to maintain',
    'Hand wash or gentle machine wash recommended'
  ],
  inStock: true,
  onSale: true,
  salePrice: 449,
  discountPercent: 18,
  images: [
    '/images/products/purple-kurta-set-1.jpg',
    '/images/products/purple-kurta-set-2.jpg',
    '/images/products/purple-kurta-set-3.jpg',
    '/images/products/purple-kurta-set-4.jpg'
  ]
  },
  {
     id: '2',
  name: 'Red Floral Printed Kurta Sharara & Dupatta Set',
  price: 599,
  category: 'Women Ethnic Wear',
  description:
    'Make a graceful statement with this elegant red floral printed ethnic set featuring a stylish A-line kurta, matching sharara pants, and a contrasting dark green dupatta. Designed with a flattering wrap-style V-neckline, delicate lace detailing, and soft floral prints, this three-piece outfit offers the perfect blend of comfort and festive elegance. Ideal for weddings, festive celebrations, family gatherings, and traditional occasions.',
  details: [
    '3-piece ethnic wear set',
    'Floral printed A-line kurta',
    'Matching printed sharara pants',
    'Solid dark green dupatta',
    'Wrap-style V-neckline',
    'Decorative lace border detailing',
    'Three-quarter sleeves',
    'Side tie-up tassels',
    'Lightweight breathable fabric',
    'Regular comfortable fit',
    'Perfect for festive and ethnic occasions',
    'Soft and skin-friendly material',
    'Hand wash or gentle machine wash recommended'
  ],
  inStock: true,
  onSale: true,
  salePrice: 499,
  discountPercent: 17,
    images: [
    '/images/products/red-floral-sharara-1.jpg',
    '/images/products/red-floral-sharara-2.jpg',
    '/images/products/red-floral-sharara-3.jpg',
    '/images/products/red-floral-sharara-4.jpg'
    ]
    },
  {
     id: '3',
  name: 'Blue Floral Printed Kurta Palazzo & Dupatta Set',
  price: 579,
  category: 'Women Ethnic Wear',
  description:
    'Refresh your ethnic wardrobe with this elegant blue floral printed three-piece set featuring a beautifully crafted A-line kurta, matching palazzo pants, and a soft chiffon dupatta. Designed with a stylish mandarin split neckline, delicate lace detailing, and an all-over floral print, this outfit offers effortless elegance for festive celebrations, family gatherings, office wear, and casual ethnic occasions.',
  details: [
    '3-piece ethnic wear set',
    'Floral printed A-line kurta',
    'Matching floral printed palazzo pants',
    'Solid blue chiffon dupatta',
    'Mandarin split neckline',
    'Decorative golden lace detailing',
    'Three-quarter sleeves',
    'Comfortable regular fit',
    'Lightweight breathable fabric',
    'Soft and skin-friendly material',
    'Ideal for festive and casual ethnic wear',
    'Easy-care fabric',
    'Hand wash or gentle machine wash recommended'
  ],
  inStock: true,
  onSale: true,
  salePrice: 499,
  discountPercent: 14,
    images: [
    '/images/products/blue-floral-kurta-set-1.jpg',
    '/images/products/blue-floral-kurta-set-2.jpg',
    '/images/products/blue-floral-kurta-set-3.jpg',
    '/images/products/blue-floral-kurta-set-4.jpg'
    ],
  },
  {
    id: '4',
  name: 'Pink Embroidered Kurta Pant & Dupatta Set',
  price: 589,
  category: 'Women Ethnic Wear',
  description:
    'Bring timeless elegance to your wardrobe with this beautiful pink embroidered three-piece ethnic set. The ensemble features a graceful straight-fit kurta with intricate white embroidery on the neckline, matching pants with lace detailing, and a lightweight embroidered organza dupatta. Designed for comfort and sophistication, this outfit is perfect for festive celebrations, family gatherings, weddings, office wear, and special occasions.',
  details: [
    '3-piece ethnic wear set',
    'Straight-fit embroidered kurta',
    'Matching straight pants',
    'Soft embroidered organza dupatta',
    'Elegant white embroidery detailing',
    'Round split neckline',
    'Three-quarter sleeves',
    'Lace detailed pant hem',
    'Lightweight breathable fabric',
    'Regular comfortable fit',
    'Perfect for festive and ethnic occasions',
    'Soft and skin-friendly material',
    'Hand wash or gentle machine wash recommended'
  ],
   inStock: true,
  onSale: true,
  salePrice: 499,
  discountPercent: 15,
  images: [
    '/images/products/pink-kurta-set-1.jpg',
    '/images/products/pink-kurta-set-2.jpg',
    '/images/products/pink-kurta-set-3.jpg',
    '/images/products/pink-kurta-set-4.jpg',
    ],
  },
  {
    id: '5',
    name: 'Sky Blue Embroidered Kurta Pant & Organza Dupatta Set',
    price: 560,
    category: 'Women Ethnic Wear',
    description:  "Elegant sky blue embroidered ethnic wear set including an A-line kurta, matching straight pants, and embroidered organza dupatta. Designed with delicate white lace detailing, this lightweight and comfortable outfit is perfect for festive occasions, parties, family gatherings, office wear, and celebrations.",
    details: ['Full-grain leather', 'Magnetic snap closure', 'Interior zip pocket', 'Adjustable shoulder strap', 'Dust bag included'],
    inStock: true,
    onSale: true,
    salePrice: 420,
    discountPercent: 25,
    images: [
      "/images/products/sky-blue-kurta-set-1.jpg",
      "/images/products/sky-blue-kurta-set-2.jpg",
      "/images/products/sky-blue-kurta-set-3.jpg"
    ],
  },
  {
    id: '6',
    name: 'Sunshine Ethnic Kurta Palazzo Set',
  price: 499,
  category: 'Fashion',
  description: "Bright yellow ethnic co-ord set featuring a sleeveless gathered kurta paired with flowy palazzo pants. Accented with elegant golden zari borders, this festive outfit offers a graceful silhouette that's perfect for celebrations, weddings, and traditional occasions.",
  details: [
    'Soft rayon blend fabric',
    'Sleeveless gathered kurta design',
    'Comfortable elastic waistband palazzo',
    'Golden zari border detailing',
    'Lightweight and breathable',
    'Round neckline',
    'Regular fit',
    'Perfect for festive and ethnic wear',
    'Hand wash separately in cold water',
    'Do not bleach'
  ],
  inStock: true,
  onSale: true,
  salePrice: 399,
  discountPercent: 20,
  images: [
    '/images/products/yellow-kurta-set-1.jpg',
    '/images/products/yellow-kurta-set-2.jpg',
    '/images/products/yellow-kurta-set-3.jpg',
    '/images/products/yellow-kurta-set-4.jpg'
  ]
  },
  {
    id: '7',
     name: 'Ivory Embroidered Kurta Set with Dupatta',
  price: 499,
  category: 'Fashion',
  description: 'Elevate your ethnic wardrobe with this elegant ivory kurta set featuring intricate golden embroidery, matching straight pants, and a lightweight embroidered organza dupatta. Designed for festive occasions, family gatherings, and celebrations, this graceful ensemble offers both comfort and timeless style.',
  details: [
    '3-piece ethnic set: Kurta, Straight Pants & Dupatta',
    'Soft silk-blend fabric with subtle sheen',
    'Intricate golden thread embroidery on neckline and sleeves',
    'Matching embroidered organza dupatta with scalloped border',
    'Straight-fit pants with functional side pocket',
    'Round neckline with embroidered placket',
    '3/4 sleeves',
    'Comfortable regular fit',
    'Ideal for festive wear, weddings, and ethnic occasions',
    'Dry clean recommended'
  ],
  inStock: true,
  onSale: true,
  salePrice: 449,
  discountPercent: 10,
  images: [
    '/images/products/ivory-kurta-set-1.jpg',
    '/images/products/ivory-kurta-set-2.jpg',
    '/images/products/ivory-kurta-set-3.jpg',
    '/images/products/ivory-kurta-set-4.jpg'
  ],
  },
  {
    id: '8',
    name: 'Floral Printed Kurta Sharara Set with Dupatta',
  price: 499,
  category: 'Women Ethnic Wear',
  description: 'Elevate your ethnic wardrobe with this elegant floral printed kurta and sharara set. Featuring intricate lace detailing on the neckline, sleeves, and dupatta, this outfit blends traditional charm with modern comfort. Perfect for festive celebrations, family gatherings, and casual ethnic occasions.',
  details: [
    '3-piece ethnic set: Kurta, Sharara & Dupatta',
    'All-over floral paisley print',
    'Soft breathable cotton blend fabric',
    'Round split neckline with lace embroidery',
    'Three-quarter sleeves with lace trim',
    'Comfortable flared sharara pants',
    'Lightweight organza dupatta with lace border',
    'Regular fit',
    'Festive and casual wear',
    'Hand wash recommended'
  ],
  inStock: true,
  onSale: true,
  salePrice: 449,
  discountPercent: 10,
  images: [
    '/images/products/floral-kurta-set-1.jpg',
    '/images/products/floral-kurta-set-2.jpg',
    '/images/products/floral-kurta-set-3.jpg',
    '/images/products/floral-kurta-set-4.jpg'
  ]
  },
  {
    id: '9',
    name: 'Ceramic Pour-Over Set',
    price: 145,
    category: 'Home',
    description: 'A matte ceramic pour-over dripper and server set for the considered morning ritual.',
    details: ['Food-safe matte glaze', 'Holds 600ml', 'Dishwasher safe', 'Includes paper filters (x20)'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800',
    ],
  },
  {
    id: '10',
    name: 'Linen Duvet Cover',
    price: 210,
    category: 'Home',
    description: 'Stonewashed French linen duvet cover — gets softer with every wash.',
    details: ['100% French linen', 'Stonewashed finish', 'Button closure', 'Available in King and Queen', 'Machine washable'],
    inStock: true,
    onSale: true,
    salePrice: 160,
    discountPercent: 24,
    images: [
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
      'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800',
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800',
    ],
  },
  {
    id: '11',
    name: 'Silk Slip Dress',
    price: 480,
    category: 'Fashion',
    description: 'Fluid silk charmeuse slip dress with adjustable spaghetti straps and a bias cut.',
    details: ['100% silk charmeuse', 'Bias cut', 'Adjustable straps', 'Hand wash only'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=800',
      'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=800',
    ],
  },
  {
    id: '12',
    name: 'Walnut Desk Organiser',
    price: 95,
    category: 'Home',
    description: 'Solid walnut desk organiser with three compartments and a cable management slot.',
    details: ['Solid walnut', 'Three compartments', 'Cable slot at rear', 'Oiled finish', 'Handmade'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1593062096033-9a26b09da705?w=800',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
    ],
  },
  {
    id: '13',
    name: 'Leather Card Holder',
    price: 85,
    category: 'Accessories',
    description: 'Slim vegetable-tanned leather card holder with three card slots and a centre pocket.',
    details: ['Vegetable-tanned leather', 'Fits 6 cards', 'Centre pocket', 'Ages beautifully'],
    inStock: true,
    onSale: true,
    salePrice: 65,
    discountPercent: 24,
    images: [
      'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800',
      'https://images.unsplash.com/photo-1559554498-d0e5e3c22e12?w=800',
    ],
  },
  {
    id: '14',
    name: 'Canvas Weekender Bag',
    price: 310,
    category: 'Accessories',
    description: 'Waxed canvas weekender with leather handles and a removable shoulder strap.',
    details: ['Waxed canvas body', 'Leather handles and trim', 'Removable strap', 'Shoe compartment', 'Waterproof lining'],
    inStock: false,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800',
      'https://images.unsplash.com/photo-1491637639811-60e2756cc1c7?w=800',
      'https://images.unsplash.com/photo-1473188588951-666fce8e7c68?w=800',
    ],
  },
  {
    id: '15',
    name: 'Ribbed Cotton Knit Set',
    price: 220,
    category: 'Fashion',
    description: 'Matching ribbed cotton lounge set: cropped long-sleeve top and wide-leg pants.',
    details: ['95% cotton 5% elastane', 'Ribbed texture', 'Relaxed fit', 'Co-ord set', 'Machine washable'],
    inStock: true,
    onSale: true,
    salePrice: 175,
    discountPercent: 20,
    images: [
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800',
      'https://images.unsplash.com/photo-1581044777550-4cfa60707c03?w=800',
    ],
  },
  {
    id: '16',
    name: 'Stoneware Mug Set (4)',
    price: 80,
    category: 'Home',
    description: 'Set of four hand-thrown stoneware mugs with a speckled matte glaze.',
    details: ['Hand-thrown stoneware', 'Set of 4', '350ml capacity', 'Microwave and dishwasher safe'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=800',
      'https://images.unsplash.com/photo-1571757767119-68b8dbed8c97?w=800',
    ],
  },
  {
    id: '17',
    name: 'Beeswax Pillar Candles (3)',
    price: 55,
    category: 'Home',
    description: 'Hand-dipped pure beeswax pillar candles with a natural honey scent.',
    details: ['100% beeswax', 'Set of 3 heights', 'Natural cotton wick', 'Burns 60–80 hours each'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1602178506645-a2d6a7698e3c?w=800',
      'https://images.unsplash.com/photo-1603905860430-04b3e04b7834?w=800',
    ],
  },
  {
    id: '18',
    name: 'Leather Belt',
    price: 130,
    category: 'Accessories',
    description: 'Full-grain leather belt with a brushed silver buckle in a 3cm width.',
    details: ['Full-grain leather', '3cm width', 'Brushed silver buckle', 'Available in 75–105cm', 'Punched in-house'],
    inStock: true,
    onSale: true,
    salePrice: 99,
    discountPercent: 24,
    images: [
      'https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=800',
      'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?w=800',
    ],
  },
  {
    id: '19',
    name: 'Linen Trench Coat',
    price: 740,
    category: 'Fashion',
    description: 'A lightweight summer trench in washed linen — structured but breathable.',
    details: ['100% washed linen', 'Double-breasted', 'Removable belt', 'Knee length', 'Dry clean only'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800',
      'https://images.unsplash.com/photo-1548624313-0396c75e4b1a?w=800',
      'https://images.unsplash.com/photo-1539533018257-33f78d900c86?w=800',
    ],
  },
  {
    id: '20',
    name: 'Wool Flat Cap',
    price: 110,
    category: 'Accessories',
    description: 'Classic flat cap in a herringbone wool blend with a satin-lined interior.',
    details: ['Wool herringbone blend', 'Satin lining', 'Adjustable back strap', 'One size fits most'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?w=800',
      'https://images.unsplash.com/photo-1521369909029-2afed882baee?w=800',
    ],
  },
  {
    id: '21',
    name: 'Oversized Blazer',
    price: 580,
    category: 'Fashion',
    description: 'A sharp oversized blazer in a fine wool blend — elevated everyday tailoring.',
    details: ['Wool blend', 'Oversized fit', 'Single button closure', 'Chest welt pocket', 'Dry clean only'],
    inStock: true,
    onSale: true,
    salePrice: 430,
    discountPercent: 26,
    images: [
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800',
      'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=800',
      'https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=800',
    ],
  },
  {
    id: '22',
    name: 'Linen Shirt Dress',
    price: 265,
    category: 'Fashion',
    description: 'Relaxed shirt dress in stonewashed linen with a belted waist and side pockets.',
    details: ['100% stonewashed linen', 'Belted waist', 'Side pockets', 'Button front', 'Machine washable'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=800',
      'https://images.unsplash.com/photo-1485968579580-b6d095142e6e?w=800',
    ],
  },
  {
    id: '23',
    name: 'Leather Oxford Shoes',
    price: 520,
    category: 'Footwear',
    description: 'Classic cap-toe oxfords in polished calfskin with a leather sole.',
    details: ['Calfskin leather upper', 'Cap-toe design', 'Leather sole', 'Goodyear welt construction', 'Available in whole sizes'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1614252369475-531eba835eb1?w=800',
      'https://images.unsplash.com/photo-1560343090-f0409e92791a?w=800',
      'https://images.unsplash.com/photo-1531310197839-ccf54634509e?w=800',
    ],
  },
  {
    id: '24',
    name: 'Knitted Beanie',
    price: 65,
    category: 'Accessories',
    description: 'A dense-knit merino beanie with a folded cuff and a relaxed fit.',
    details: ['100% merino wool', 'Folded cuff', 'Ribbed knit', 'One size fits most'],
    inStock: true,
    onSale: true,
    salePrice: 45,
    discountPercent: 31,
    images: [
      'https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?w=800',
      'https://images.unsplash.com/photo-1510598969022-c4c6c5d05769?w=800',
    ],
  },
  {
    id: '25',
    name: 'Rattan Pendant Light',
    price: 175,
    category: 'Home',
    description: 'Hand-woven rattan pendant light shade with a warm, diffused glow.',
    details: ['Hand-woven rattan', 'E27 bulb fitting', '40cm diameter', 'Cord length 120cm', 'Bulb not included'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800',
      'https://images.unsplash.com/photo-1540932239986-30128078f3c5?w=800',
    ],
  },
  {
    id: '26',
    name: 'Merino Base Layer Set',
    price: 195,
    category: 'Fashion',
    description: 'Lightweight merino wool base layer top and leggings for all-season layering.',
    details: ['100% merino wool', 'Flatlock seams', 'Moisture wicking', 'Top and leggings set', 'Machine washable'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?w=800',
      'https://images.unsplash.com/photo-1556906781-9a412961a28c?w=800',
    ],
  },
  {
    id: '27',
    name: 'Marble Cheese Board',
    price: 90,
    category: 'Home',
    description: 'Solid white marble cheese board with a natural veined surface and rubber feet.',
    details: ['White Carrara marble', '35 x 20cm', 'Anti-slip rubber feet', 'Wipe clean only'],
    inStock: true,
    onSale: true,
    salePrice: 68,
    discountPercent: 24,
    images: [
      'https://images.unsplash.com/photo-1452195100486-9cc805987862?w=800',
      'https://images.unsplash.com/photo-1541167760496-1628856ab772?w=800',
    ],
  },
  {
    id: '28',
    name: 'Crossbody Leather Bag',
    price: 340,
    category: 'Accessories',
    description: 'Compact crossbody in pebbled leather with an adjustable strap and gold hardware.',
    details: ['Pebbled leather', 'Gold-tone hardware', 'Adjustable strap', 'Interior card slots', 'Zip closure'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800',
      'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=800',
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800',
    ],
  },
  {
    id: '29',
    name: 'Denim Straight Leg Jeans',
    price: 210,
    category: 'Fashion',
    description: 'Classic straight-leg jeans in a rigid selvedge denim with a mid-rise waist.',
    details: ['Selvedge denim', 'Mid-rise waist', 'Straight leg', 'Five-pocket styling', 'Machine wash cold'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800',
      'https://images.unsplash.com/photo-1555689502-c4b22d76c56f?w=800',
    ],
  },
  {
    id: '30',
    name: 'Acacia Wood Salad Bowl',
    price: 60,
    category: 'Home',
    description: 'Large hand-carved acacia wood salad bowl with a natural oiled finish.',
    details: ['Hand-carved acacia', '30cm diameter', 'Food-safe oil finish', 'Hand wash only'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
      'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800',
    ],
  },
  {
    id: '31',
    name: 'Leather Watch Strap',
    price: 75,
    category: 'Accessories',
    description: 'Handmade horween leather watch strap with quick-release pins.',
    details: ['Horween leather', 'Quick-release pins', '20mm lug width', 'Available in tan and black', 'Antique silver hardware'],
    inStock: true,
    onSale: true,
    salePrice: 55,
    discountPercent: 27,
    images: [
      'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=800',
      'https://images.unsplash.com/photo-1594534475808-b18fc33b045e?w=800',
    ],
  },
  {
    id: '32',
    name: 'Cotton Poplin Shirt',
    price: 155,
    category: 'Fashion',
    description: 'Crisp cotton poplin shirt with a relaxed fit and a single chest pocket.',
    details: ['100% cotton poplin', 'Relaxed fit', 'Chest pocket', 'Button-down collar', 'Machine washable'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800',
      'https://images.unsplash.com/photo-1603252109303-2751441dd157?w=800',
      'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=800',
    ],
  },
  {
    id: '33',
    name: 'Wool Scarf',
    price: 120,
    category: 'Accessories',
    description: 'A generously sized lambswool scarf in a classic herringbone weave.',
    details: ['100% lambswool', '200 x 35cm', 'Fringed ends', 'Dry clean only'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=800',
      'https://images.unsplash.com/photo-1517438476312-10d79c077509?w=800',
    ],
  },
  {
    id: '34',
    name: 'Slip-On Canvas Shoes',
    price: 120,
    category: 'Footwear',
    description: 'Minimalist slip-on shoes in washed canvas with a vulcanised rubber sole.',
    details: ['Washed canvas upper', 'Vulcanised rubber sole', 'Elastic side gussets', 'Unisex sizing'],
    inStock: true,
    onSale: true,
    salePrice: 89,
    discountPercent: 26,
    images: [
      'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800',
      'https://images.unsplash.com/photo-1465453869711-7e174808ace9?w=800',
    ],
  },
  {
    id: '35',
    name: 'Linen Throw Blanket',
    price: 135,
    category: 'Home',
    description: 'Softly washed linen throw in a natural undyed finish — perfect for sofa draping.',
    details: ['100% washed linen', '130 x 170cm', 'Fringed edges', 'Natural undyed', 'Machine washable'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800',
    ],
  },
  {
    id: '36',
    name: 'Terracotta Planter Set',
    price: 70,
    category: 'Home',
    description: 'Set of three hand-thrown terracotta planters in graduating sizes.',
    details: ['Hand-thrown terracotta', 'Set of 3', 'Drainage holes included', 'Frost-resistant glaze'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800',
      'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800',
    ],
  },
  {
    id: '37',
    name: 'Raw Denim Jacket',
    price: 340,
    category: 'Fashion',
    description: 'Classic trucker jacket in raw selvedge denim that fades beautifully over time.',
    details: ['Raw selvedge denim', 'Chest snap pockets', 'Adjustable side tabs', 'Machine wash cold', 'Fades with wear'],
    inStock: false,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?w=800',
      'https://images.unsplash.com/photo-1551537482-f2075a1d41f2?w=800',
      'https://images.unsplash.com/photo-1523205771623-e0faa4d2813d?w=800',
    ],
  },
  {
    id: '38',
    name: 'Leather Bifold Wallet',
    price: 95,
    category: 'Accessories',
    description: 'Slim bifold wallet in full-grain leather with eight card slots and a bill compartment.',
    details: ['Full-grain leather', '8 card slots', 'Bill compartment', 'Slim profile', 'Gift boxed'],
    inStock: true,
    onSale: true,
    salePrice: 72,
    discountPercent: 24,
    images: [
      'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800',
      'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800',
    ],
  },
  {
    id: '39',
    name: 'Wool Lounge Trousers',
    price: 245,
    category: 'Fashion',
    description: 'Relaxed lounge trousers in a brushed wool blend — refined enough for the office.',
    details: ['Brushed wool blend', 'Elasticated waistband', 'Side pockets', 'Tapered leg', 'Dry clean only'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800',
      'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=800',
    ],
  },
  {
    id: '40',
    name: 'Brass Desk Lamp',
    price: 220,
    category: 'Home',
    description: 'Adjustable brass desk lamp with a weighted base and a fabric cord.',
    details: ['Solid brass', 'Adjustable arm and head', 'E14 bulb fitting', 'Fabric cord 180cm', 'Bulb not included'],
    inStock: true,
    onSale: true,
    salePrice: 170,
    discountPercent: 23,
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800',
      'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=800',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
    ],
  },
 {
    id: '41',
    name: 'Bamboo Cutting Board',
    price: 45,
    category: 'Home',
    description: 'Large end-grain bamboo cutting board with juice grooves and non-slip feet.',
    details: ['End-grain bamboo', '40 x 28cm', 'Juice groove', 'Non-slip rubber feet', 'Hand wash only'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800',
      'https://images.unsplash.com/photo-1528712306091-ed0763094c98?w=800',
    ],
  },
  {
    id: '42',
    name: 'Suede Loafers',
    price: 410,
    category: 'Footwear',
    description: 'Penny loafers in soft suede with a leather sole and classic coin slot.',
    details: ['Soft suede upper', 'Leather sole', 'Penny slot detail', 'Leather lining', 'Available in whole sizes'],
    inStock: true,
    onSale: true,
    salePrice: 299,
    discountPercent: 27,
    images: [
      'https://images.unsplash.com/photo-1582897085656-c636d006a246?w=800',
      'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=800',
      'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=800',
    ],
  },
  {
    id: '43',
    name: 'Silk Pyjama Set',
    price: 320,
    category: 'Fashion',
    description: 'Luxurious silk pyjama set with piped trim and a relaxed straight-leg cut.',
    details: ['100% silk', 'Piped trim detail', 'Elastic waistband', 'Breast pocket', 'Hand wash only'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800',
      'https://images.unsplash.com/photo-1583744946564-b52ac1c389c8?w=800',
    ],
  },
  {
    id: '44',
    name: 'Cast Iron Skillet',
    price: 85,
    category: 'Home',
    description: 'Pre-seasoned 25cm cast iron skillet for stovetop and oven use.',
    details: ['Pre-seasoned cast iron', '25cm diameter', 'Oven safe to 260°C', 'Helper handle', 'Hand wash only'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1585515320310-259814833e62?w=800',
      'https://images.unsplash.com/photo-1593759608142-e976bca35418?w=800',
    ],
  },
  {
    id: '45',
    name: 'Ribbed Merino Beanie',
    price: 70,
    category: 'Accessories',
    description: 'Fine-ribbed merino wool beanie with a slouchy fit and turned-up cuff.',
    details: ['100% merino wool', 'Fine-rib knit', 'Slouchy fit', 'Turned-up cuff', 'One size'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1510598969022-c4c6c5d05769?w=800',
      'https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?w=800',
    ],
  },
  {
    id: '46',
    name: 'Linen Napkin Set (6)',
    price: 65,
    category: 'Home',
    description: 'Set of six stonewashed linen napkins with a hemstitched border.',
    details: ['100% stonewashed linen', 'Set of 6', '45 x 45cm', 'Hemstitched edge', 'Machine washable'],
    inStock: true,
    onSale: true,
    salePrice: 48,
    discountPercent: 26,
    images: [
      'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=800',
      'https://images.unsplash.com/photo-1543352634-99a5d50ae78e?w=800',
    ],
  },
  {
    id: '47',
    name: 'Trench Coat Belt',
    price: 95,
    category: 'Accessories',
    description: 'Wide woven leather belt designed for layering over coats and dresses.',
    details: ['Full-grain leather', '5cm width', 'Gold-tone buckle', 'Sizes XS–XL'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1624222247344-550fb60583dc?w=800',
      'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800',
    ],
  },
  {
    id: '48',
    name: 'Knit Polo Shirt',
    price: 175,
    category: 'Fashion',
    description: 'Fine cotton knit polo with a three-button placket and ribbed collar.',
    details: ['100% cotton', 'Three-button placket', 'Ribbed collar and cuffs', 'Regular fit', 'Machine washable'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=800',
      'https://images.unsplash.com/photo-1620799139507-2a76f79a2f4d?w=800',
      'https://images.unsplash.com/photo-1607345366928-199ea26cfe3e?w=800',
    ],
  },
  {
    id: '49',
    name: 'Brass Candlestick Pair',
    price: 110,
    category: 'Home',
    description: 'Pair of solid turned brass candlesticks in two heights with a polished finish.',
    details: ['Solid brass', 'Set of 2 heights (15cm and 22cm)', 'Fits standard taper candles', 'Polished finish'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1602178506645-a2d6a7698e3c?w=800',
      'https://images.unsplash.com/photo-1603905860430-04b3e04b7834?w=800',
    ],
  },
  {
    id: '50',
    name: 'Running Shoes',
    price: 190,
    category: 'Footwear',
    description: 'Lightweight knit running shoes with responsive foam cushioning.',
    details: ['Engineered knit upper', 'Responsive foam midsole', 'Rubber outsole', 'Reflective details', 'Available in half sizes'],
    inStock: true,
    onSale: true,
    salePrice: 140,
    discountPercent: 26,
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800',
      'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800',
      'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800',
    ],
  },
  {
    id: '51',
    name: 'Leather Passport Holder',
    price: 60,
    category: 'Accessories',
    description: 'Slim full-grain leather passport holder with two card slots and a pen loop.',
    details: ['Full-grain leather', 'Two card slots', 'Pen loop', 'Fits all passport sizes', 'Gift boxed'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1553279768-865429fa0078?w=800',
      'https://images.unsplash.com/photo-1452421822248-d4c2b47f0c81?w=800',
    ],
  },
  {
    id: '52',
    name: 'Oversized Hoodie',
    price: 145,
    category: 'Fashion',
    description: 'Heavyweight 400gsm cotton hoodie in a boxy oversized fit.',
    details: ['400gsm fleece cotton', 'Oversized fit', 'Kangaroo pocket', 'Ribbed cuffs and hem', 'Machine washable'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=800',
      'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=800',
    ],
  },
  {
    id: '53',
    name: 'Glass Carafe Set',
    price: 75,
    category: 'Home',
    description: 'Borosilicate glass carafe and two matching tumblers for water or wine.',
    details: ['Borosilicate glass', 'Carafe 1L + 2 tumblers 300ml', 'Dishwasher safe', 'Lead-free'],
    inStock: true,
    onSale: true,
    salePrice: 56,
    discountPercent: 25,
    images: [
      'https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800',
      'https://images.unsplash.com/photo-1559839914-17aae19cec71?w=800',
    ],
  },
  {
    id: '54',
    name: 'Leather Sandals',
    price: 280,
    category: 'Footwear',
    description: 'Handcrafted leather sandals with an anatomical footbed and adjustable buckle straps.',
    details: ['Full-grain leather straps', 'Anatomical cork footbed', 'Adjustable buckles', 'Leather outsole', 'Handmade in Portugal'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1603487742131-4160ec999306?w=800',
      'https://images.unsplash.com/photo-1562183241-b937e95585b6?w=800',
      'https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=800',
    ],
  },
  {
    id: '55',
    name: 'Organic Cotton Tee',
    price: 75,
    category: 'Fashion',
    description: 'Essential crewneck tee in 220gsm organic cotton with a slightly boxy cut.',
    details: ['220gsm GOTS organic cotton', 'Boxy fit', 'Crew neck', 'Double-stitched hem', 'Machine washable'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800',
      'https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=800',
    ],
  },
  {
    id: '56',
    name: 'Oak Photo Frame Set (3)',
    price: 80,
    category: 'Home',
    description: 'Set of three solid oak photo frames in 10x15, 13x18, and 20x25cm sizes.',
    details: ['Solid oak', 'Set of 3 sizes', 'Glass front', 'Landscape and portrait compatible', 'Wall and tabletop use'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=800',
      'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=800',
    ],
  },
  {
    id: '57',
    name: 'Wool Blanket Coat',
    price: 860,
    category: 'Fashion',
    description: 'A dramatic single-button blanket coat in a double-faced wool blend.',
    details: ['Double-faced wool blend', 'Single button closure', 'Oversized fit', 'Side slit pockets', 'Dry clean only'],
    inStock: true,
    onSale: true,
    salePrice: 650,
    discountPercent: 24,
    images: [
      'https://images.unsplash.com/photo-1548624313-0396c75e4b1a?w=800',
      'https://images.unsplash.com/photo-1539533018257-33f78d900c86?w=800',
      'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800',
    ],
  },
  {
    id: '58',
    name: 'Satin Hair Scrunchie Set',
    price: 28,
    category: 'Accessories',
    description: 'Set of five satin scrunchies in neutral tones — gentle on all hair types.',
    details: ['100% satin', 'Set of 5 colours', 'Gentle elastic', 'One size'],
    inStock: true,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1562259929-b4e1fd3aef09?w=800',
      'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800',
    ],
  },
  {
    id: '59',
    name: 'Velvet Cushion Cover (2)',
    price: 55,
    category: 'Home',
    description: 'Set of two velvet cushion covers with a hidden zip in a deep jewel tone.',
    details: ['Cotton velvet', 'Set of 2', '50 x 50cm', 'Hidden zip closure', 'Machine washable'],
    inStock: false,
    onSale: false,
    images: [
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
      'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
    ],
  },
  {
    id: '60',
    name: 'Leather Notebook Cover',
    price: 115,
    category: 'Accessories',
    description: 'Wrap-style leather notebook cover that fits A5 notebooks with a pen loop and card pocket.',
    details: ['Full-grain leather', 'Fits A5 notebooks', 'Pen loop', 'Card pocket', 'Notebook not included'],
    inStock: true,
    onSale: true,
    salePrice: 88,
    discountPercent: 23,
    images: [
      'https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=800',
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800',
    ],
  },
]


export function getProductById(id: string) {
  return products.find((product) => product.id === id)
}
